-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    indent = {
      enable = false,
    },
    ensure_installed = {
      "lua",
      "vim",
      "qmljs",
      "qmldir",
      "typst",
      "typescript",
      "tsx",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "asm",
      "bash",
      "dockerfile",
      "gitignore",
      "go",
      "http",
      "html",
      "css",
      "scss",
      "rust",
      "python",
      "c",
      "cpp",
      "toml",
      "yaml",
      "xml",
      "fish",
      "c_sharp",
      "cmake",
      "csv",
      "desktop",
      "diff",
      "disassembly",
      "latex",
      "llvm",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "nginx",
      "objdump",
      "passwd",
      "regex",
      "slint",
      "ssh_config",
      -- add more arguments for adding more treesitter parsers
    },
  },
}
